# Minimal config to enable NMEA output on ZED-F9P
ublox_dgnss_node:
  ros__parameters:
    device: "/dev/ttyACM1"
    baudrate: 115200
    DEVICE_FAMILY: "F9P"
    FRAME_ID: "gnss"
    
    # ENABLE NMEA output over USB
    CFG_USBOUTPROT_NMEA: 1
    
    # Also enable some NMEA message types
    CFG_MSGOUT_NMEA_ID_GGA_USB: 1  # GGA: Fix data
    CFG_MSGOUT_NMEA_ID_GLL_USB: 1  # GLL: Lat/Lon
    CFG_MSGOUT_NMEA_ID_GSA_USB: 1  # GSA: DOP and active satellites
    CFG_MSGOUT_NMEA_ID_GSV_USB: 1  # GSV: Satellites in view
    CFG_MSGOUT_NMEA_ID_RMC_USB: 1  # RMC: Recommended minimum
    CFG_MSGOUT_NMEA_ID_VTG_USB: 1  # VTG: Track and ground speed
    
    # Update rate: 5 Hz
    CFG_RATE_MEAS: 200
    CFG_RATE_NAV: 1

